image: Visual Studio 2017

environment:
  matrix:
    - platform: x86
      GENERATOR: "Visual Studio 15 2017"
    - platform: x64
      GENERATOR: "Visual Studio 15 2017 Win64"

build_script:
  - cmd: md x
  - cmd: cd x
  - cmd: cmake "-G%GENERATOR%" -DCMAKE_BUILD_TYPE=Release -DLIBNDT_ENABLE_CI_TESTING_=ON ..
  - cmd: cmake --build . -- /nologo
  - cmd: ctest -V -C Release -a -j8
